function Graticule(a,b){function c(a,b,c,e){var n;n=Math.PI/10;c=c.getContext("2d");c=new LineDrawer(0,b,a,c);for(a=0;5.5>a;a+=1)b=-Math.PI/2+a*n,c.projectDraw(e,b);c.stroke();for(a=0;5.5>a;a+=1)b=a*n,c.projectDraw(e,b);c.stroke()}function e(a,b,c,e){var n;n=2*Math.PI/19;c=c.getContext("2d");c=new LineDrawer(0,b,a,c);for(a=0;20>a;a+=1)b=-Math.PI+a*n,c.projectDraw(b,e);c.stroke()}this.render=function(d,f,h,g){var n,l,m;n=g.getContext("2d");n.save();n.translate(g.width/2,g.height/2);applyStyle(a,n);
for(l=0;l<360/b;l+=1){for(m=-Math.PI+l*b/180*Math.PI-f;m<-Math.PI;)m+=2*Math.PI;for(;m>Math.PI;)m-=2*Math.PI;c(d,h,g,m)}for(l=1;l<180/b;l+=1)f=-Math.PI/2+l*b/180*Math.PI,e(d,h,g,f);if("function"!==typeof d.isPoleInsideGraticule||!1===d.isPoleInsideGraticule())c(d,h,g,-Math.PI),c(d,h,g,Math.PI);e(d,h,g,-Math.PI/2);e(d,h,g,Math.PI/2);n.restore()};this.load=function(a,b,c){}}
function Layer(a,b){var c=this;this.dbfFile=this.shpFile=null;this.render=function(a,d,f,h){if(null!==c.shpFile)switch(c.shpFile.header.shapeType){case ShpType.SHAPE_POLYGON:case ShpType.SHAPE_POLYLINE:var g,n,l;g=h.getContext("2d");g.save();g.translate(h.width/2,h.height/2);applyStyle(b,g);d=new LineDrawer(d,f,a,g);for(a=0;a<c.shpFile.records.length;a+=1){f=c.shpFile.records[a];f=f.shape;for(h=0;h<f.rings.length;h+=1){n=f.rings[h];for(l=0;l<n.length;l+=1)d.intersectProjectDraw(n[l].x,n[l].y);d.stroke()}}g.restore();
break;case ShpType.SHAPE_POINT:var m,q,r,s,u,v;l=[];r=h.width/2;s=-h.height/2;g=h.getContext("2d");g.save();u="undefined"!==typeof b&&b.hasOwnProperty("fillStyle");v="undefined"!==typeof b&&b.hasOwnProperty("strokeStyle");u&&"undefined"!==typeof b.fillStyle&&(g.fillStyle=b.fillStyle);v&&"undefined"!==typeof b.strokeStyle&&(g.strokeStyle=b.strokeStyle);"undefined"!==typeof b&&(b.hasOwnProperty("lineWidth")&&"undefined"!==typeof b.lineWidth)&&(g.lineWidth=b.lineWidth);for(n=0;n<c.shpFile.records.length;n+=
1){m=c.shpFile.records[n];m=m.shape;q=m.x;for(q-=d;q<-Math.PI;)q+=2*Math.PI;for(;q>Math.PI;)q-=2*Math.PI;m=m.y;a.forward(q,m,l);m=l[0]*f+r;q=h.height-l[1]*f+s;u&&"undefined"!==typeof b.fillStyle&&g.fillRect(m-2,q-2,4,4);v&&"undefined"!==typeof b.strokeStyle&&g.strokeRect(m-2,q-2,4,4)}g.restore()}};this.load=function(b){function d(){alert("Failed to load "+a)}function f(){alert("Failed to load "+a)}function h(a){c.shpFile=new ShpFile(a.binaryResponse);switch(c.shpFile.header.shapeType){case ShpType.SHAPE_POLYGON:case ShpType.SHAPE_POLYLINE:a=
c.shpFile.records;var d=Math.PI/180,h,f,g,n,v,x,k,p,t,w,y,A,z;n=0;for(h=a.length;n<h;n+=1){z=a[n].shape;t=Number.MAX_VALUE;w=-Number.MAX_VALUE;y=Number.MAX_VALUE;A=-Number.MAX_VALUE;v=0;for(f=z.rings.length;v<f;v+=1){x=z.rings[v];k=0;for(g=x.length;k<g;k+=1)p=x[k].x*d,p>w&&(w=p),p<t&&(t=p),p>Math.PI?p=Math.PI:p<-Math.PI&&(p=-Math.PI),x[k].x=p,p=x[k].y*d,p>Math.PI/2?p=Math.PI/2:p<-Math.PI/2&&(p=-Math.PI/2),p>A&&(A=p),p<y&&(y=p),x[k].y=p}z.box.xMin=t;z.box.xMax=w;z.box.yMin=y;z.box.yMax=A}break;case ShpType.SHAPE_POINT:a=
c.shpFile.records;f=Math.PI/180;d=0;for(h=a.length;d<h;d+=1)g=a[d].shape,g.x*=f,g.y*=f}null!==c.dbfFile&&b.render()}function g(a){c.dbfFile=new DbfFile(a.binaryResponse);null!==c.shpFile&&b.render()}try{new BinaryAjax(a+".shp",h,d),new BinaryAjax(a+".dbf",g,f)}catch(n){alert(n)}}}function pointLineDistanceSquare(a,b,c,e,d,f){d-=c;f-=e;a=d*(e-b)-(c-a)*f;return a*a/(d*d+f*f)}function adjustLongitude(a,b){for(a-=b;a<-Math.PI;)a+=2*Math.PI;for(;a>Math.PI;)a-=2*Math.PI;return a}
function SphericalRotation(a){var b,c;b=Math.sin(a);c=Math.cos(a);this.getPoleLat=function(){return a};this.transform=function(a,d,f){var h,g;h=Math.sin(a);g=Math.cos(a);a=Math.sin(d);d=Math.cos(d);g*=d;f[0]=Math.atan2(d*h,b*g+c*a);a=b*a-c*g;f[1]=Math.asin(a)};this.transformInv=function(a,d,f){var h=Math.sin(a),g=Math.cos(a);a=Math.sin(d);d=Math.cos(d);g*=d;f[0]=Math.atan2(d*h,b*g-c*a);f[1]=Math.asin(b*a+c*g)}}
function LineDrawer(a,b,c,e){function d(a,l,q,x){var k,p,t=[];p=[];if(!(50<(x+=1)))a=adjustLongitude(a,q),c.forward(a,l,t),m?isFinite(t[0])&&isFinite(t[1])&&(e.beginPath(),e.moveTo(t[0]*b,-t[1]*b),m=!1):(q=0.5*(g+a),k=0.5*(n+l),c.forward(q,k,p),p=pointLineDistanceSquare(p[0],p[1],f,h,t[0],t[1]),isFinite(p)?(p>r&&(d(q,k,0,x),d(a,l,0,x)),e.lineTo(t[0]*b,-t[1]*b)):(e.stroke(),m=!0)),f=t[0],h=t[1],g=a,n=l}var f,h,g,n,l,m=!0,q,r;new SphericalRotation(Math.PI/4);q=0.25/b;r=q*q;this.stroke=function(){e.stroke();
m=!0};this.projectIntersectingLineTo=function(b,c,h,e){var f,g,t,w,n,m,l;f=b-h;g=c-e;t=Math.PI+a;w=-Math.PI+a;b>t?(n=Math.PI,l=e+g*(t-h)/f,m=-Math.PI):h>t?(n=-Math.PI,l=e+g*(t-h)/f,m=Math.PI):b<w?(n=-Math.PI,l=e+g*(w-h)/f,m=Math.PI):h<w&&(n=Math.PI,l=e+g*(w-h)/f,m=-Math.PI);d(n,l,0,1);this.stroke();d(m,l,0,1);d(b,c,a,1)};this.projectDraw=function(a,b){d(a,b,0,1)};this.intersectProjectDraw=function(b,c){var h;m?l=h=b-a<-Math.PI||b-a>Math.PI:h=b-a<-Math.PI||b-a>Math.PI;l!==h?(l=h,this.projectIntersectingLineTo(b,
c,g,n)):d(b,c,a,1)}}function backingScale(a){return(window.devicePixelRatio||1)/(a.webkitBackingStorePixelRatio||a.mozBackingStorePixelRatio||a.msBackingStorePixelRatio||a.oBackingStorePixelRatio||a.backingStorePixelRatio||1)}function applyStyle(a,b){var c,e;if("undefined"!==typeof a)for(c in a)a.hasOwnProperty(c)&&(e=a[c],"lineWidth"===c&&(e*=backingScale(b)),b[c]=e)}
function Map(a,b){var c,e=!0,d=0,f=1;c={forward:function(a,b,c){c[0]=a;c[1]=b}};this.load=function(){var b;for(b=0;b<a.length;b+=1)a[b].load(this)};this.getCanvas=function(){return b};this.getProjection=function(){return c};this.setProjection=function(a){c=a;this.render()};this.getCentralLongitude=function(){return d};this.setCentralLongitude=function(a){isNaN(a)||(d=a,d>Math.PI?d-=2*Math.PI:d<-Math.PI&&(d+=2*Math.PI),this.render())};this.setDraw=function(a){e=a;this.render()};this.isDrawn=function(){return e};
this.clear=function(){b.getContext("2d").clearRect(0,0,b.width,b.height)};this.getScale=function(){return f};this.setScale=function(a){f=a;this.render()};this.getMaximumHorizontalScale=function(){var a,d=[];"function"===typeof c.getGraticuleWidth?a=c.getGraticuleWidth():(c.forward(Math.PI,0,d),a=2*d[0],c.forward(Math.PI,Math.PI/2,d),a=Math.max(a,d[0]));return b.width/a};this.getMaximumVerticalScale=function(){var a,d=[];"function"===typeof c.getGraticuleHeight?a=c.getGraticuleHeight():(c.forward(0,
Math.PI/2,d),a=2*d[1],c.forward(Math.PI,Math.PI/2,d),a=Math.max(a,d[1]));return b.height/a};this.getGraticuleWidth=function(){var a,b=[];"function"===typeof c.getGraticuleWidth?a=c.getGraticuleWidth():(c.forward(Math.PI,0,b),a=2*b[0],c.forward(Math.PI,Math.PI/2,b),a=Math.max(a,b[0]));return a};this.getGraticuleHeight=function(){var a,b=[];"function"===typeof c.getGraticuleHeight?a=c.getGraticuleHeight():(c.forward(0,Math.PI/2,b),a=2*b[1],c.forward(Math.PI,Math.PI/2,b),a=Math.max(a,b[1]));return a};
this.scaleMapToCanvas=function(){var a,b;a=this.getMaximumHorizontalScale();b=this.getMaximumVerticalScale();this.setScale(Math.min(a,b))};this.render=function(){var h;this.clear();if(e)for(h=0;h<a.length;h+=1)a[h].render(c,d,f,b)};this.resize=function(a,c){var d=backingScale(b.getContext("2d"));b.setAttribute("width",a*d);b.setAttribute("height",c*d);this.scaleMapToCanvas();this.render()}}function createMap(a,b,c,e,d){a=new Map(a,c);a.setProjection(b);a.resize(e,d);a.load();return a}
function BinaryFileWrapper(a){this.position=0;this.bigEndian=!0;this.getByte=function(){var b=a.getByteAt(this.position);this.position++;return b};this.getLength=function(){return a.getLength()};this.getSByte=function(){var b=a.getSByteAt(this.position);this.position++;return b};this.getShort=function(){var b=a.getShortAt(this.position,this.bigEndian);this.position+=2;return b};this.getSShort=function(){var b=a.getSShortAt(this.position,this.bigEndian);this.position+=2;return b};this.getLong=function(){var b=
a.getLongAt(this.position,this.bigEndian);this.position+=4;return b};this.getSLong=function(){var b=a.getSLongAt(this.position,this.bigEndian);this.position+=4;return b};this.getString=function(b){var c=a.getStringAt(this.position,b);this.position+=b;return c};this.getDoubleAt=function(b,c){var e=a.getLongAt(b+(c?0:4),c),d=a.getLongAt(b+(c?4:0),c),f=(e>>20&2047)-1023;return 1*(e>>31?-1:1)*(e&1048575|1048576)/Math.pow(2,20)*Math.pow(2,f)+1*d/Math.pow(2,52)*Math.pow(2,f)};this.getDouble=function(){var a=
this.getDoubleAt(this.position,this.bigEndian);this.position+=8;return a};this.getChar=function(){var b=a.getCharAt(this.position);this.position++;return b}}function DbfFile(a){this.src=new BinaryFileWrapper(a);(new Date).getTime();this.header=new DbfHeader(this.src);(new Date).getTime();(new Date).getTime();this.records=[];for(a=0;a<this.header.recordCount;a++){var b=this.getRecord(a);this.records.push(b)}(new Date).getTime()}
DbfFile.prototype.getRecord=function(a){if(a>this.header.recordCount)throw new DbfError("",DbfError.ERROR_OUTOFBOUNDS);this.src.position=this.header.recordsOffset+a*this.header.recordSize;this.src.bigEndian=!1;return new DbfRecord(this.src,this.header)};
function DbfHeader(a){a.bigEndian=!1;this.version=a.getSByte();this.updateYear=1900+a.getByte();this.updateMonth=a.getByte();this.updateDay=a.getByte();this.recordCount=a.getLong();this.headerSize=a.getShort();this.recordSize=a.getShort();a.position+=2;this.incompleteTransaction=a.getByte();this.encrypted=a.getByte();a.position+=12;this.mdx=a.getByte();this.language=a.getByte();a.position+=2;for(this.fields=[];13!=a.getSByte();)a.position-=1,this.fields.push(new DbfField(a));this.recordsOffset=this.headerSize+
1}function DbfField(a){this.name=this.readZeroTermANSIString(a);a.position+=10-this.name.length;this.type=a.getByte();this.address=a.getLong();this.length=a.getByte();this.decimals=a.getByte();a.position+=2;this.id=a.getByte();a.position+=2;this.setFlag=a.getByte();a.position+=7;this.indexFlag=a.getByte()}DbfField.prototype.readZeroTermANSIString=function(a){for(var b=[],c;c=a.getByte();)b[b.length]=String.fromCharCode(c);return b.join("")};
function DbfRecord(a,b){this.offset=a.position;this.values={};for(var c=0;c<b.fields.length;c++){var e=b.fields[c];this.values[e.name]=a.getString(e.length)}}
var BinaryFile=function(a,b,c){var e=a,d=b||0,f=0;this.getRawData=function(){return e};"string"==typeof a?(f=c||e.length,this.getByteAt=function(a){return e.charCodeAt(a+d)&255}):"unknown"==typeof a&&(f=c||IEBinary_getLength(e),this.getByteAt=function(a){return IEBinary_getByteAt(e,a+d)});this.getLength=function(){return f};this.getSByteAt=function(a){a=this.getByteAt(a);return 127<a?a-256:a};this.getShortAt=function(a,b){var c=b?(this.getByteAt(a)<<8)+this.getByteAt(a+1):(this.getByteAt(a+1)<<8)+
this.getByteAt(a);0>c&&(c+=65536);return c};this.getSShortAt=function(a,b){var c=this.getShortAt(a,b);return 32767<c?c-65536:c};this.getLongAt=function(a,b){var c=this.getByteAt(a),d=this.getByteAt(a+1),e=this.getByteAt(a+2),f=this.getByteAt(a+3),c=b?(((c<<8)+d<<8)+e<<8)+f:(((f<<8)+e<<8)+d<<8)+c;0>c&&(c+=4294967296);return c};this.getSLongAt=function(a,b){var c=this.getLongAt(a,b);return 2147483647<c?c-4294967296:c};this.getStringAt=function(a,b){for(var c=[],d=a,e=0;d<a+b;d++,e++)c[e]=String.fromCharCode(this.getByteAt(d));
return c.join("")};this.getCharAt=function(a){return String.fromCharCode(this.getByteAt(a))};this.toBase64=function(){return window.btoa(e)};this.fromBase64=function(a){e=window.atob(a)}},BinaryAjax=function(){function a(){var a=null;window.XMLHttpRequest?a=new XMLHttpRequest:window.ActiveXObject&&(a=new ActiveXObject("Microsoft.XMLHTTP"));return a}function b(b,c,f,h){var g=a();g?(c&&("undefined"!=typeof g.onload?g.onload=function(){"200"==g.status?c(this,h):f&&f();g=null}:g.onreadystatechange=function(){4==
g.readyState&&("200"==g.status?c(this,h):f&&f(),g=null)}),g.open("HEAD",b,!0),g.send(null)):f&&f()}function c(b,c,f,h,g,n,l){var m=a();if(m){var q=0;g&&!n&&(q=g[0]);var r=0;g&&(r=g[1]-g[0]+1);c&&("undefined"!=typeof m.onload?m.onload=function(){"200"==m.status||"206"==m.status||"0"==m.status?(m.binaryResponse=new BinaryFile(m.responseText,q,r),m.fileSize=l||m.getResponseHeader("Content-Length"),c(m,h)):f&&f();m=null}:m.onreadystatechange=function(){if(4==m.readyState){if("200"==m.status||"206"==m.status||
"0"==m.status){var a={status:m.status,binaryResponse:new BinaryFile(m.responseBody,q,r),fileSize:l||m.getResponseHeader("Content-Length")};c(a,h)}else f&&f();m=null}});m.open("GET",b,!0);m.overrideMimeType&&m.overrideMimeType("text/plain; charset=x-user-defined");g&&n&&m.setRequestHeader("Range","bytes="+g[0]+"-"+g[1]);m.setRequestHeader("If-Modified-Since","Sat, 1 Jan 1970 00:00:00 GMT");m.send(null)}else f&&f()}return function(a,d,f,h,g){g?b(a,function(b){var l=parseInt(b.getResponseHeader("Content-Length"),
10);b=b.getResponseHeader("Accept-Ranges");var m;m=g[0];0>g[0]&&(m+=l);c(a,d,f,h,[m,m+g[1]-1],"bytes"==b,l)}):c(a,d,f,h)}}();document.write("<script type='text/vbscript'>\r\nFunction IEBinary_getByteAt(strBinary, iOffset)\r\n\tIEBinary_getByteAt = AscB(MidB(strBinary,iOffset+1,1))\r\nEnd Function\r\nFunction IEBinary_getLength(strBinary)\r\n\tIEBinary_getLength = LenB(strBinary)\r\nEnd Function\r\n\x3c/script>\r\n");
window.CanvasRenderingContext2D||function(){function a(a){var b=a.srcElement;switch(a.propertyName){case "width":b.style.width=b.attributes.width.nodeValue+"px";b.getContext().clearRect();break;case "height":b.style.height=b.attributes.height.nodeValue+"px",b.getContext().clearRect()}}function b(a){a=a.srcElement;a.firstChild&&(a.firstChild.style.width=a.clientWidth+"px",a.firstChild.style.height=a.clientHeight+"px")}function c(){return[[1,0,0],[0,1,0],[0,0,1]]}function e(a,b){for(var d=c(),e=0;3>
e;e++)for(var f=0;3>f;f++){for(var h=0,g=0;3>g;g++)h+=a[e][g]*b[g][f];d[e][f]=h}return d}function d(a,b){b.fillStyle=a.fillStyle;b.lineCap=a.lineCap;b.lineJoin=a.lineJoin;b.lineWidth=a.lineWidth;b.miterLimit=a.miterLimit;b.shadowBlur=a.shadowBlur;b.shadowColor=a.shadowColor;b.shadowOffsetX=a.shadowOffsetX;b.shadowOffsetY=a.shadowOffsetY;b.strokeStyle=a.strokeStyle;b.arcScaleX_=a.arcScaleX_;b.arcScaleY_=a.arcScaleY_}function f(a){var b,c=1;a=String(a);if("rgb"==a.substring(0,3)){b=a.indexOf("(",3);
var d=a.indexOf(")",b+1),d=a.substring(b+1,d).split(",");b="#";for(var e=0;3>e;e++)b+=x[Number(d[e])];4==d.length&&"a"==a.substr(3,1)&&(c=d[3])}else b=a;return[b,c]}function h(a){switch(a){case "butt":return"flat";case "round":return"round";default:return"square"}}function g(a){this.m_=c();this.mStack_=[];this.aStack_=[];this.currentPath_=[];this.fillStyle=this.strokeStyle="#000";this.lineWidth=1;this.lineJoin="miter";this.lineCap="butt";this.miterLimit=1*u;this.globalAlpha=1;this.canvas=a;var b=
a.ownerDocument.createElement("div");b.style.width=a.clientWidth+"px";b.style.height=a.clientHeight+"px";b.style.overflow="hidden";b.style.position="absolute";a.appendChild(b);this.element_=b;this.arcScaleY_=this.arcScaleX_=1}function n(a){this.type_=a;this.radius2_=this.radius1_=0;this.colors_=[];this.focus_={x:0,y:0}}function l(){}var m=Math,q=m.round,r=m.sin,s=m.cos,u=10,v=u/2,m={init:function(a){var b=a||document;if(/MSIE/.test(navigator.userAgent)&&!window.opera){var c=this;b.attachEvent("onreadystatechange",
function(){c.init_(b)})}},init_:function(a){if("complete"==a.readyState){a.namespaces.g_vml_||a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml");a.createStyleSheet().cssText="canvas{display:inline-block;overflow:hidden;text-align:left;width:300px;height:150px}g_vml_\\:*{behavior:url(#default#VML)}";a=a.getElementsByTagName("canvas");for(var b=0;b<a.length;b++)a[b].getContext||this.initElement(a[b])}},fixElement_:function(a){var b=a.outerHTML,c=a.ownerDocument.createElement(b);if("/>"!=b.slice(-2)){for(var b=
"/"+a.tagName,d;(d=a.nextSibling)&&d.tagName!=b;)d.removeNode();d&&d.removeNode()}a.parentNode.replaceChild(c,a);return c},initElement:function(c){c=this.fixElement_(c);c.getContext=function(){return this.context_?this.context_:this.context_=new g(this)};c.attachEvent("onpropertychange",a);c.attachEvent("onresize",b);var d=c.attributes;d.width&&d.width.specified?c.style.width=d.width.nodeValue+"px":c.width=c.clientWidth;d.height&&d.height.specified?c.style.height=d.height.nodeValue+"px":c.height=
c.clientHeight;return c}};m.init();for(var x=[],k=0;16>k;k++)for(var p=0;16>p;p++)x[16*k+p]=k.toString(16)+p.toString(16);k=g.prototype;k.clearRect=function(){this.element_.innerHTML="";this.currentPath_=[]};k.beginPath=function(){this.currentPath_=[]};k.moveTo=function(a,b){this.currentPath_.push({type:"moveTo",x:a,y:b});this.currentX_=a;this.currentY_=b};k.lineTo=function(a,b){this.currentPath_.push({type:"lineTo",x:a,y:b});this.currentX_=a;this.currentY_=b};k.bezierCurveTo=function(a,b,c,d,e,f){this.currentPath_.push({type:"bezierCurveTo",
cp1x:a,cp1y:b,cp2x:c,cp2y:d,x:e,y:f});this.currentX_=e;this.currentY_=f};k.quadraticCurveTo=function(a,b,c,d){a=this.currentX_+2/3*(a-this.currentX_);b=this.currentY_+2/3*(b-this.currentY_);this.bezierCurveTo(a,b,a+(c-this.currentX_)/3,b+(d-this.currentY_)/3,c,d)};k.arc=function(a,b,c,d,e,f){c*=u;var h=f?"at":"wa",g=a+s(d)*c-v;d=b+r(d)*c-v;var m=a+s(e)*c-v;e=b+r(e)*c-v;g==m&&!f&&(g+=0.125);this.currentPath_.push({type:h,x:a,y:b,radius:c,xStart:g,yStart:d,xEnd:m,yEnd:e})};k.rect=function(a,b,c,d){this.moveTo(a,
b);this.lineTo(a+c,b);this.lineTo(a+c,b+d);this.lineTo(a,b+d);this.closePath()};k.strokeRect=function(a,b,c,d){this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+d);this.lineTo(a,b+d);this.closePath();this.stroke()};k.fillRect=function(a,b,c,d){this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+d);this.lineTo(a,b+d);this.closePath();this.fill()};k.createLinearGradient=function(a,b,c,d){return new n("gradient")};k.createRadialGradient=function(a,b,c,d,e,f){d=
new n("gradientradial");d.radius1_=c;d.radius2_=f;d.focus_.x=a;d.focus_.y=b;return d};k.drawImage=function(a,b){var c,d,e,f,h,g,m,n;e=a.runtimeStyle.width;f=a.runtimeStyle.height;a.runtimeStyle.width="auto";a.runtimeStyle.height="auto";var l=a.width,k=a.height;a.runtimeStyle.width=e;a.runtimeStyle.height=f;if(3==arguments.length)c=arguments[1],d=arguments[2],h=g=0,m=e=l,n=f=k;else if(5==arguments.length)c=arguments[1],d=arguments[2],e=arguments[3],f=arguments[4],h=g=0,m=l,n=k;else if(9==arguments.length)h=
arguments[1],g=arguments[2],m=arguments[3],n=arguments[4],c=arguments[5],d=arguments[6],e=arguments[7],f=arguments[8];else throw"Invalid number of arguments";var p=this.getCoords_(c,d),s=[];s.push(" <g_vml_:group",' coordsize="',10*u,",",10*u,'"',' coordorigin="0,0"',' style="width:',10,";height:",10,";position:absolute;");if(1!=this.m_[0][0]||this.m_[0][1]){var r=[];r.push("M11='",this.m_[0][0],"',","M12='",this.m_[1][0],"',","M21='",this.m_[0][1],"',","M22='",this.m_[1][1],"',","Dx='",q(p.x/u),
"',","Dy='",q(p.y/u),"'");var x=this.getCoords_(c+e,d),v=this.getCoords_(c,d+f);c=this.getCoords_(c+e,d+f);p.x=Math.max(p.x,x.x,v.x,c.x);p.y=Math.max(p.y,x.y,v.y,c.y);s.push("padding:0 ",q(p.x/u),"px ",q(p.y/u),"px 0;filter:progid:DXImageTransform.Microsoft.Matrix(",r.join(""),", sizingmethod='clip');")}else s.push("top:",q(p.y/u),"px;left:",q(p.x/u),"px;");s.push(' ">','<g_vml_:image src="',a.src,'"',' style="width:',u*e,";"," height:",u*f,';"',' cropleft="',h/l,'"',' croptop="',g/k,'"',' cropright="',
(l-h-m)/l,'"',' cropbottom="',(k-g-n)/k,'"'," />","</g_vml_:group>");this.element_.insertAdjacentHTML("BeforeEnd",s.join(""))};k.stroke=function(a){var b=[],c=f(a?this.fillStyle:this.strokeStyle),d=c[0],c=c[1]*this.globalAlpha;b.push("<g_vml_:shape",' fillcolor="',d,'"',' filled="',Boolean(a),'"',' style="position:absolute;width:',10,";height:",10,';"',' coordorigin="0 0" coordsize="',10*u," ",10*u,'"',' stroked="',!a,'"',' strokeweight="',this.lineWidth,'"',' strokecolor="',d,'"',' path="');for(var e=
null,g=null,m=null,n=null,l=0;l<this.currentPath_.length;l++){var k=this.currentPath_[l];if("moveTo"==k.type){b.push(" m ");var p=this.getCoords_(k.x,k.y);b.push(q(p.x),",",q(p.y))}else if("lineTo"==k.type)b.push(" l "),p=this.getCoords_(k.x,k.y),b.push(q(p.x),",",q(p.y));else if("close"==k.type)b.push(" x ");else if("bezierCurveTo"==k.type){b.push(" c ");var p=this.getCoords_(k.x,k.y),s=this.getCoords_(k.cp1x,k.cp1y),k=this.getCoords_(k.cp2x,k.cp2y);b.push(q(s.x),",",q(s.y),",",q(k.x),",",q(k.y),
",",q(p.x),",",q(p.y))}else if("at"==k.type||"wa"==k.type){b.push(" ",k.type," ");var p=this.getCoords_(k.x,k.y),s=this.getCoords_(k.xStart,k.yStart),r=this.getCoords_(k.xEnd,k.yEnd);b.push(q(p.x-this.arcScaleX_*k.radius),",",q(p.y-this.arcScaleY_*k.radius)," ",q(p.x+this.arcScaleX_*k.radius),",",q(p.y+this.arcScaleY_*k.radius)," ",q(s.x),",",q(s.y)," ",q(r.x),",",q(r.y))}if(p){if(null==e||p.x<e)e=p.x;if(null==m||p.x>m)m=p.x;if(null==g||p.y<g)g=p.y;if(null==n||p.y>n)n=p.y}}b.push(' ">');if("object"==
typeof this.fillStyle){d=a="50%";a=m-e;g=n-g;l=a>g?a:g;a=q(100*(this.fillStyle.focus_.x/a)+50)+"%";d=q(100*(this.fillStyle.focus_.y/g)+50)+"%";g=[];"gradientradial"==this.fillStyle.type_?(n=100*(this.fillStyle.radius1_/l),e=100*(this.fillStyle.radius2_/l)-n):(n=0,e=100);s=k=p=m=null;this.fillStyle.colors_.sort(function(a,b){return a.offset-b.offset});for(l=0;l<this.fillStyle.colors_.length;l++){r=this.fillStyle.colors_[l];g.push(r.offset*e+n,"% ",r.color,",");if(r.offset>m||null==m)m=r.offset,p=r.color;
if(r.offset<k||null==k)k=r.offset,s=r.color}g.pop();b.push("<g_vml_:fill",' color="',s,'"',' color2="',p,'"',' type="',this.fillStyle.type_,'"',' focusposition="',a,", ",d,'"',' colors="',g.join(""),'"',' opacity="',c,'" />')}else a?b.push('<g_vml_:fill color="',d,'" opacity="',c,'" />'):b.push("<g_vml_:stroke",' opacity="',c,'"',' joinstyle="',this.lineJoin,'"',' miterlimit="',this.miterLimit,'"',' endcap="',h(this.lineCap),'"',' weight="',this.lineWidth,'px"',' color="',d,'" />');b.push("</g_vml_:shape>");
this.element_.insertAdjacentHTML("beforeEnd",b.join(""));this.currentPath_=[]};k.fill=function(){this.stroke(!0)};k.closePath=function(){this.currentPath_.push({type:"close"})};k.getCoords_=function(a,b){return{x:u*(a*this.m_[0][0]+b*this.m_[1][0]+this.m_[2][0])-v,y:u*(a*this.m_[0][1]+b*this.m_[1][1]+this.m_[2][1])-v}};k.save=function(){var a={};d(this,a);this.aStack_.push(a);this.mStack_.push(this.m_);this.m_=e(c(),this.m_)};k.restore=function(){d(this.aStack_.pop(),this);this.m_=this.mStack_.pop()};
k.translate=function(a,b){this.m_=e([[1,0,0],[0,1,0],[a,b,1]],this.m_)};k.transform=function(a,b,c,d,f,h){this.m_=e([[a,b,0],[c,d,0],[f,h,1]],this.m_)};k.rotate=function(a){var b=s(a);a=r(a);this.m_=e([[b,a,0],[-a,b,0],[0,0,1]],this.m_)};k.scale=function(a,b){this.arcScaleX_*=a;this.arcScaleY_*=b;this.m_=e([[a,0,0],[0,b,0],[0,0,1]],this.m_)};k.clip=function(){};k.arcTo=function(){};k.createPattern=function(){return new l};n.prototype.addColorStop=function(a,b){b=f(b);this.colors_.push({offset:1-a,
color:b})};G_vmlCanvasManager=m;CanvasRenderingContext2D=g;CanvasGradient=n;CanvasPattern=l}();
function AlbersConic(){var a,b,c,e;this.toString=function(){return"Albers Conic"};this.initialize=function(d,f,h){var g,n;if(1E-10>Math.abs(f+h))throw c=NaN,Error("Standard latitudes of Albers conic too close to equator");g=Math.cos(f);n=Math.sin(f);c=1E-10<=Math.abs(f-h)?0.5*(n+Math.sin(h)):n;e=2*c;a=g*g+e*n;b=Math.sqrt(a-e*Math.sin(d))/c};this.forward=function(d,f,h){f=a-e*Math.sin(f);0>f&&(h[0]=NaN,h[1]=NaN);f=Math.sqrt(f)/c;d*=c;h[0]=f*Math.sin(d);h[1]=b-f*Math.cos(d)};this.initialize(0.25*Math.PI,
0.25*Math.PI,0.25*Math.PI)}function ArdenClose(){var a=88/180*Math.PI;this.toString=function(){return"Arden-Close"};this.forward=function(b,c,e){var d;c>a?c=a:c<-a&&(c=-a);d=Math.log(Math.tan(Math.PI/4+0.5*c));c=Math.sin(c);e[0]=b;e[1]=(d+c)/2}}
function AspectAdaptiveCylindrical(){var a=[9.684,-33.44,43.13,-19.77,-0.569,-0.875,7.002,-5.948,-0.509,3.333,-6.705,4.148],b=[0.0186,-0.0215,-1.179,1.837],c=Math.PI/2,e=0.25*Math.PI,d,f,h,g,n,l;this.toString=function(){return"Aspect Adaptive Cylindrical"};this.getMinAspectRatio=function(){return 0.3};this.getMaxAspectRatio=function(){return 1};this.getAspectRatio=function(a){return d};this.setAspectRatio=function(e){d=Math.max(Math.min(e,1),0.3);var q,r,s;0.7<d?(e=a[0]+0.7*(a[1]+0.7*(a[2]+0.7*a[3])),
q=a[4]+0.7*(a[5]+0.7*(a[6]+0.7*a[7])),r=a[8]+0.7*(a[9]+0.7*(a[10]+0.7*a[11])),s=c*(e+c*c*(q+c*c*r)),f=0.7*e*Math.PI/s,h=0.7*q*Math.PI/s,g=0.7*r*Math.PI/s,e=b[0]+d*b[1],q=b[2]+d*b[3],r=c-0.7,r*=e+r*r*q,s=d-0.7,n=e*Math.PI*s/r,l=q*Math.PI*s/r):(e=a[0]+d*(a[1]+d*(a[2]+d*a[3])),q=a[4]+d*(a[5]+d*(a[6]+d*a[7])),r=a[8]+d*(a[9]+d*(a[10]+d*a[11])),s=c*(e+c*c*(q+c*c*r)),f=e*d*Math.PI/s,h=q*d*Math.PI/s,g=r*d*Math.PI/s,n=l=0)};this.forward=function(a,b,c){var s=b*b;c[0]=a;c[1]=b*(f+s*(h+s*g));0.7<d&&b>e&&(a=
b-0.7,c[1]+=a*(n+a*a*l));0.7<d&&b<-e&&(a=b+0.7,c[1]+=a*(n+a*a*l))}}function Bonne(){var a=85/180*Math.PI,b=1/Math.tan(a);this.toString=function(){return"Bonne (Equal Area)"};this.getGraticuleHeight=function(){return 6};this.getStandardParallel=function(){return a};this.setStandardParallel=function(c){a=c;b=1/Math.tan(a)};this.forward=function(c,e,d){var f=b+a-e;c=c*Math.cos(e)/f;d[0]=f*Math.sin(c);d[1]=b-f*Math.cos(c)}}
function Braun2(){this.toString=function(){return"Braun2"};this.forward=function(a,b,c){c[0]=a;c[1]=1.4*Math.sin(b)/(0.4+Math.cos(b))}}function Canters1(){this.toString=function(){return"Canters Modified Sinusoidal I"};this.forward=function(a,b,c){var e=b*b,d=e*e;c[0]=a*Math.cos(b)/(1.1966+-0.387*e+-0.038*d);c[1]=b*(1.1966+-0.129*e+-0.0076*d)}}
function Canters2(){var a=3*-0.0753;this.toString=function(){return"Canters Modified Sinusoidal II"};this.forward=function(b,c,e){var d=c*c,f=d*d;e[0]=b*Math.cos(c)/(1.1481+a*d+-0.075*f);e[1]=c*(1.1481+-0.0753*d+-0.015*f)}}function CentralCylindrical(){var a=80/180*Math.PI;this.toString=function(){return"Central Cylindrical"};this.forward=function(b,c,e){c>a?c=a:c<-a&&(c=-a);e[0]=b;e[1]=Math.tan(c)}}
function CylindricalStereographic(){var a=Math.cos(30/180*Math.PI);this.toString=function(){return"Cylindrical Stereographic"};this.getStandardParallel=function(){return Math.acos(a)};this.setStandardParallel=function(b){a=Math.cos(b)};this.forward=function(b,c,e){e[0]=b*a;e[1]=(1+a)*Math.tan(c/2)}}
function Eckert4(){this.toString=function(){return"Eckert IV"};this.forward=function(a,b,c){var e,d,f,h;e=3.5707963267948966*Math.sin(b);d=b*b;b*=0.895168+d*(0.0218849+0.00826809*d);for(h=6;0<h;--h)if(f=Math.cos(b),d=Math.sin(b),b-=d=(b+d*(f+2)-e)/(1+f*(f+2)-d*d),1E-7>Math.abs(d)){c[0]=0.4222382003157712*a*(1+Math.cos(b));c[1]=1.3265004281770023*Math.sin(b);return}c[0]=0.4222382003157712*a;c[1]=0>b?-1.3265004281770023:1.3265004281770023};this.inverse=function(a,b,c){b/=1.3265004;var e=Math.asin(b);
c[0]=a/(0.4222382*(1+Math.cos(e)));c[1]=Math.asin((e+b*Math.cos(e)+2*b)/(2+Math.PI/2))}}function EqualAreaCylindrical(){var a=Math.cos(30/180*Math.PI);this.toString=function(){return"Cylindrical Equal-Area"};this.getStandardParallel=function(){return Math.acos(a)};this.setStandardParallel=function(b){a=Math.cos(b)};this.forward=function(b,c,e){e[0]=b*a;e[1]=Math.sin(c)/a}}
function Equirectangular(){var a=Math.cos(30/180*Math.PI);this.toString=function(){return"Equirectangular"};this.getStandardParallel=function(){return Math.acos(a)};this.setStandardParallel=function(b){a=Math.cos(b)};this.forward=function(b,c,e){e[0]=b*a;e[1]=c};this.inverse=function(b,c,e){e[0]=b/a;e[1]=c}}
function Hammer(a){this.toString=function(){switch(a){case 0:return"Quartic Authalic";case 0.5:return"Hammer";default:return"Hammer Customized"}};this.forward=function(b,c,e){var d=Math.cos(c),f;b*=a;f=Math.sqrt(2/(1+d*Math.cos(b)));e[0]=f*d*Math.sin(b)/a;e[1]=f*Math.sin(c)};this.inverse=function(b,c,e){b*=a;var d=Math.sqrt(1-0.25*(b*b+c*c)),f=2*d*d-1;1E-10>Math.abs(f)?(e[0]=NaN,e[1]=NaN):(e[0]=Math.atan2(b*d,f)/a,e[1]=Math.asin(d*c))};this.setW=function(b){a=b;0.999999<=a?a=0.999999:0>a&&(a=0);0===
a&&(this.forward=this.quarticAuthalicForward,this.inverse=this.quarticAuthalicInverse)};this.setW(0===arguments.length?0.5:a);this.getW=function(){return a}}
function Hufnagel(){function a(){var a,d,l,q,k;h=[];g=[];n=[];r=!1;for(a=0;a<f;a+=1){d=e*a/(f-1);0===a?l=0:a===f-1?l=Math.PI/2:(l=Math.sin(2*d),q=Math.sin(4*d),k=Math.sin(6*d),l=Math.asin(0.25/Math.PI*m*m*(2*d+(1+b-0.5*c)*l+0.5*(b+c)*q+0.5*c*k)));q=Math.sqrt(1+b*Math.cos(2*d)+c*Math.cos(4*d));q*=Math.sin(d);if(0<a&&(q<g[a-1]||l<h[a-1]))r=!0,q=g[a-1],l=h[a-1];h.push(l);g.push(q);n.push(d)}}var b=0,c=0,e=Math.PI/2,d=2,f=101,h,g,n,l,m,q,r=!1;this.forward=function(a,d,e){var g,k,p=0;g=0;var r=Math.PI*
Math.sin(d);if(0!==d){a:{var w,y;y=Math.abs(d);for(var A=0,z=f-1;z>=A;){p=Math.floor((A+z)/2);k=h[Math.max(0,p-1)];w=h[p];if(k<y&&w>=y){y-=k;k=w-k;k=y/k;w=n[Math.max(0,p-1)];p=n[p];p=k*(p-w)+w;p=0>d?-p:p;break a}w<y?A=p+1:z=p-1}p=0}if(Math.abs(p)<Math.PI/2){do{k=2*p;d=l/4*(k+(1+b-c/2)*Math.sin(k)+(b+c)/2*Math.sin(2*k)+c/2*Math.sin(3*k))-r;k=l/2*(1+(1+b-c/2)*Math.cos(k)+(b+c)*Math.cos(2*k)+3*c/2*Math.cos(3*k));d/=k;g+=1;if(!isFinite(d)||100<g){e[0]=NaN;e[1]=NaN;return}p-=d}while(1E-6<Math.abs(d))}}g=
Math.sqrt(1+b*Math.cos(2*p)+c*Math.cos(4*p));e[0]=m*g*q*a/Math.PI*Math.cos(p);e[1]=m*g/q*Math.sin(p)};this.init=function(){var f=[],g;l=4*Math.PI/(2*e+(1+b-c/2)*Math.sin(2*e)+(b+c)/2*Math.sin(4*e)+c/2*Math.sin(6*e));m=Math.sqrt(l);q=1;a();this.forward(Math.PI,0,f);g=f[0];this.forward(0,Math.PI/2,f);q=Math.sqrt(d/(g/f[1]));a()};this.init();this.setA=function(a){b=a;this.init()};this.setB=function(a){c=a;this.init()};this.setPsiMax=function(a){e=a;this.init()};this.setAspectRatio=function(a){d=a;this.init()};
this.isGraticuleFolding=function(){return r};this.toString=function(){return"Hufnagel"}}function Kavrayskiy1(){var a=Math.PI/2,b=70/180*Math.PI,c,e;c=Math.log(Math.tan(0.5*(a+b)));e=1/Math.cos(b);this.toString=function(){return"Kavrayskiy I"};this.forward=function(d,f,h){h[0]=d;h[1]=f>b?(f-b)*e+c:f<-b?(f+b)*e-c:Math.log(Math.tan(0.5*(a+f)))}}
function KharchenkoShabanova(){var a=Math.cos(10/180*Math.PI);this.toString=function(){return"Kharchenko-Shabanova"};this.forward=function(b,c,e){var d=c*c;e[0]=b*a;e[1]=c*(0.99+d*(0.0026263+0.10734*d))}}
function LambertAzimuthalEqualAreaPolar(){var a=Math.PI/4;this.toString=function(){return"Lambert Azimuthal Equal Area - Polar"};this.forward=function(b,c,e){c=2*Math.sin(a-0.5*c);e[0]=c*Math.sin(b);e[1]=c*-Math.cos(b)};this.getGraticuleWidth=function(){return 4};this.getGraticuleHeight=function(){return 4};this.isPoleInsideGraticule=function(){return!0}}
function LambertAzimuthalOblique(){var a=1,b=0;this.toString=function(){return"Lambert Azimuthal Oblique"};this.initialize=function(c){a=Math.cos(c);b=Math.sin(c)};this.forward=function(c,e,d){var f=Math.sin(e);e=Math.cos(e);var h=Math.cos(c),g=Math.sin(c);c=1+b*f+a*e*h;c=Math.sqrt(2/c);d[0]=c*e*g;d[1]=c*(a*f-b*e*h)};this.initialize(45*Math.PI/180)}
function LambertEqualAreaCylindrical(){this.toString=function(){return"Lambert Cylindrical Equal-Area"};this.forward=function(a,b,c){c[0]=a;c[1]=Math.sin(b)};this.inverse=function(a,b,c){c[0]=a;c[1]=Math.asin(b)}}function Mercator(){var a=Math.PI/2;this.toString=function(){return"Mercator"};this.forward=function(b,c,e){e[0]=b;e[1]=1.4844222297453322<c?Math.PI:-1.4844222297453322>c?-Math.PI:Math.log(Math.tan(0.5*(a+c)))}}
function Miller(){this.toString=function(){return"Miller"};this.forward=function(a,b,c){c[0]=a;c[1]=1.25*Math.log(Math.tan(Math.PI/4+0.4*b))}}function Miller2(){this.toString=function(){return"Miller II"};this.forward=function(a,b,c){c[0]=a;c[1]=1.5*Math.log(Math.tan(Math.PI/4+b/3))}}function MillerPerspective(){this.toString=function(){return"Miller Perspective"};this.forward=function(a,b,c){c[0]=a;c[1]=Math.sin(b/2)+Math.tan(b/2)}}
function MillerTransformation(){var a=Math.PI/2,b=1.5,c=1.5;this.toString=function(){return"Miller Transformation"};this.getM=function(){return c};this.setM=function(a){c=a};this.getN=function(){return b};this.setN=function(a){b=a};this.getAspectRatio=function(){return b*Math.log(Math.tan(0.5*a*(1+1/b)))/Math.PI};this.setAspectRatio=function(e){if(0.5>=e)c=b=1E4;else{for(var d=1.05,f=1,h,g;1E-4<Math.abs(f);)g=0.5*a*(1+1/d),f=d*Math.log(Math.tan(g))-e*Math.PI,h=Math.log(Math.tan(g)),g=Math.tan(g)*
Math.cos(g)*Math.cos(g)*d,d-=f/=h-0.5*a/g;c=b=d}};this.forward=function(e,d,f){f[0]=e;f[1]=c*Math.log(Math.tan(0.5*(a+d/b)))}}
function Mollweide(){var a,b,c;this.toString=function(){return"Mollweide"};(function(){var e=Math.PI/2,d,f=e+e;d=Math.sin(e);e=Math.sqrt(2*Math.PI*d/(f+Math.sin(f)));a=2*e/Math.PI;b=e/d;c=f+Math.sin(f)})();this.forward=function(e,d,f){var h,g,n;h=c*Math.sin(d);for(n=10;0!==n&&!(d-=g=(d+Math.sin(d)-h)/(1+Math.cos(d)),1E-7>Math.abs(g));n--);d=0===n?0>d?-Math.PI/2:Math.PI/2:0.5*d;f[0]=a*e*Math.cos(d);f[1]=b*Math.sin(d)};this.inverse=function(a,b,c){var h,g;h=0.70710678118655*b;b=Math.asin(h);g=Math.cos(b);
c[0]=1.11072073453959*a/g;c[1]=Math.asin(2*(b+h*g)/Math.PI)}}function NaturalEarth(){this.toString=function(){return"Natural Earth"};this.forward=function(a,b,c){var e=b*b,d=e*e;c[0]=a*(0.8707-0.131979*e+d*(-0.013791+d*(0.003971*e-0.001529*d)));c[1]=b*(1.007226+e*(0.015085+d*(-0.044475+0.028874*e-0.005916*d)))}}function Pavlov(){this.toString=function(){return"Pavlov"};this.forward=function(a,b,c){var e;e=b*b*b;c[0]=a;c[1]=b-0.1531/3*e-0.00534*e*b*b}}
function Robinson(){this.toString=function(){return"Robinson"};this.forward=function(a,b,c){var e=b*b;c[0]=a*(0.8507-e*(0.145+0.0104*e));c[1]=b*(0.9642-e*(0.0013+0.0129*e))}}function Sinusoidal(){this.toString=function(){return"Sinusoidal (Equal Area)"};this.forward=function(a,b,c){c[0]=a*Math.cos(b);c[1]=b};this.inverse=function(a,b,c){c[0]=a/Math.cos(b);c[1]=b}}
function Strebe1995(){var a=1.35,b=new Eckert4,c=new Mollweide,e=new Hammer;this.setScaleFactor=function(b){a=b};this.setForward1=function(a){b=a};this.setForward2=function(a){e=a};this.setInverse=function(a){c=a};this.toString=function(){return"Strebe 1995 (Equal Area)"};this.forward=function(d,f,h){b.forward(d,f,h);c.inverse(h[0]*a,h[1]/a,h);e.forward(h[0],h[1],h);h[0]/=a;h[1]*=a}}
function Tobler1(){this.toString=function(){return"Tobler I"};this.forward=function(a,b,c){c[0]=a;c[1]=b*(1+b*b/6)}}function Tobler2(){this.toString=function(){return"Tobler II"};this.forward=function(a,b,c){var e=b*b;c[0]=a;c[1]=b*(1+e/6+e*e/24)}}
function TransformableLambert(){function a(a,b,g){var h,r;a*=e;b=c*Math.sin(b);h=Math.sqrt(1-b*b);r=1+h*Math.cos(a);r=Math.sqrt(2/r);g[0]=d*r*h*Math.sin(a);g[1]=f*r*b}function b(a,b,c){c[0]=a*g;c[1]=Math.sin(b)/g}var c,e,d,f,h,g;this.initialize=function(n,l,m){1E-10>n&&1E-10>l?(this.forward=b,g=Math.sqrt(m/Math.PI)):(this.forward=a,n=Math.max(n,1E-10),l=Math.max(l,1E-10),c=Math.sin(l),e=n/Math.PI,l=Math.sqrt(m*Math.sin(l/2)/Math.sin(n/2)),m=Math.sqrt(c*e),d=l/m,f=1/(l*m));h=n===Math.PI};this.isPoleInsideGraticule=
function(){return h};this.getGraticuleWidth=function(){var a=[];this.forward(Math.PI-1E-6,0,a);return 2*a[0]};this.initialize(Math.PI/2,Math.PI/4,Math.sqrt(2))}
function TransverseTransformableLambert(){var a,b,c,e,d;this.initialize=function(f,h,g){f=Math.max(f,1E-7);h=Math.max(h,1E-7);a=Math.sin(h);b=f/Math.PI;f=Math.sqrt(g*Math.sin(h/2)/Math.sin(f/2));h=Math.sqrt(a*b);c=f/h;e=1/(f*h);d=1.5===g};this.forward=function(d,h,g){var n,l;d+=Math.PI/2;n=Math.cos(d);l=Math.cos(h);d=Math.atan2(l*Math.sin(d),Math.sin(h));d*=b;h=a*-l*n;n=Math.sqrt(1-h*h);l=1+n*Math.cos(d);l=Math.sqrt(2/l);g[1]=-c*l*n*Math.sin(d);g[0]=e*l*h};this.getGraticuleWidth=function(){return 4};
this.getGraticuleHeight=function(){return 4};this.isPoleInsideGraticule=function(){return d};this.initialize(Math.PI/2,Math.PI/4,1.5)}function Urmayev2(){this.toString=function(){return"Urmayev II"};this.forward=function(a,b,c){var e=b*b;c[0]=a;c[1]=b*(1+0.1275561329783*e+0.0133641090422587*e*e)}}function Urmayev3(){this.toString=function(){return"Urmayev III"};this.forward=function(a,b,c){c[0]=a;c[1]=b*(0.92813433+1.11426959/3*b*b)}}
function Wagner7(a){var b,c,e,d;this.toString=function(){return"Wagner VII"+(1!==a?" Customized":"")};this.forward=function(a,h,g){var n,l;h=b*Math.sin(h);n=Math.sqrt(1-h*h);l=Math.sqrt(2/(1+n*Math.cos(a*=c)));g[0]=e*l*n*Math.sin(a);g[1]=d*l*h};this.setW=function(f){var h;a=f;1<=a?a=1:1E-10>a&&(a=1E-10);b=Math.sin(65/180*Math.PI)*a+1-a;c=1/3*a+1-a;f=Math.sqrt((1.0745992166936478*a+1-a)/Math.sin(Math.PI/2*c));h=Math.sqrt(b*c);e=f/h;d=1/(f*h)};this.setW(0===arguments.length?1:a)}
function WagnerPseudocylindrical(){var a,b,c;this.toString=function(){return"Wagner Pseudocylindrical"};this.forward=function(e,d,f){this.setW(61.9/180*Math.PI,2.03);var h,g;d=a*Math.sin(d);h=Math.sqrt(1-d*d);g=Math.sqrt(2/(1+h));f[0]=b*g*h*e;f[1]=c*g*d};this.inverse=function(e,d,f){this.setW(65/180*Math.PI,2);sinO_2=d/(2*c);cosO_2=Math.sqrt(1-sinO_2*sinO_2);f[0]=e/b*cosO_2/(2*cosO_2*cosO_2-1);f[1]=Math.asin(2*sinO_2*cosO_2/a)};this.setW=function(e,d){1E-10>e&&(e=1E-10);a=Math.sin(e);var f=Math.sqrt(2*
d*Math.sin(e/2)/Math.PI),h=Math.sqrt(a);b=f/h;c=1/(f*h);console.log("CA",b);console.log("CB",c);console.log("m",a)}}function ShpFile(a){a=new BinaryFileWrapper(a);(new Date).getTime();this.header=new ShpHeader(a);(new Date).getTime();(new Date).getTime();for(this.records=[];;)try{this.records.push(new ShpRecord(a))}catch(b){b.id!==ShpError.ERROR_NODATA&&alert(b);break}(new Date).getTime()}
var ShpType={SHAPE_UNKNOWN:-1,SHAPE_NULL:0,SHAPE_POINT:1,SHAPE_POLYLINE:3,SHAPE_POLYGON:5,SHAPE_MULTIPOINT:8,SHAPE_POINTZ:11,SHAPE_POLYLINEZ:13,SHAPE_POLYGONZ:15,SHAPE_MULTIPOINTZ:18,SHAPE_POINTM:21,SHAPE_POLYLINEM:23,SHAPE_POLYGONM:25,SHAPE_MULTIPOINTM:28,SHAPE_MULTIPATCH:31};
function ShpHeader(a){100>a.getLength()&&alert("Not a valid shape file header (too small)");9994!=a.getSLong()&&alert("Not a valid signature. Expected 9994");a.position+=20;this.fileLength=a.getSLong();a.bigEndian=!1;this.version=a.getSLong();this.shapeType=a.getSLong();this.boundsXY={x:a.getDouble(),y:a.getDouble(),width:a.getDouble(),height:a.getDouble()};this.boundsZ={x:a.getDouble(),y:a.getDouble()};this.boundsM={x:a.getDouble(),y:a.getDouble()}}
function ShpRecord(a){var b=a.getLength()-a.position;if(0==b)throw new ShpError("No Data",ShpError.ERROR_NODATA);if(8>b)throw new ShpError("Not a valid record header (too small)");a.bigEndian=!0;this.number=a.getSLong();this.contentLength=a.getSLong();this.contentLengthBytes=2*this.contentLength-4;a.bigEndian=!1;this.shapeType=a.getSLong();switch(this.shapeType){case ShpType.SHAPE_POINT:this.shape=new ShpPoint(a,this.contentLengthBytes);break;case ShpType.SHAPE_POINTZ:this.shape=new ShpPointZ(a,this.contentLengthBytes);
break;case ShpType.SHAPE_POLYGON:this.shape=new ShpPolygon(a,this.contentLengthBytes);break;case ShpType.SHAPE_POLYLINE:this.shape=new ShpPolyline(a,this.contentLengthBytes);break;case ShpType.SHAPE_MULTIPATCH:case ShpType.SHAPE_MULTIPOINT:case ShpType.SHAPE_MULTIPOINTM:case ShpType.SHAPE_MULTIPOINTZ:case ShpType.SHAPE_POINTM:case ShpType.SHAPE_POLYGONM:case ShpType.SHAPE_POLYGONZ:case ShpType.SHAPE_POLYLINEZ:case ShpType.SHAPE_POLYLINEM:throw new ShpError(this.shapeType+" Shape type is currently unsupported by this library");
default:throw new ShpError("Encountered unknown shape type ("+this.shapeType+")");}}function ShpPoint(a,b){this.type=ShpType.SHAPE_POINT;if(a){if(a.getLength()-a.position<b)throw new ShpError("Not a Point record (too small)");this.x=0<b?a.getDouble():NaN;this.y=0<b?a.getDouble():NaN}}
function ShpPointZ(a,b){this.type=ShpType.SHAPE_POINTZ;if(a){if(a.getLength()-a.position<b)throw new ShpError("Not a Point record (too small)");this.x=0<b?a.getDouble():NaN;this.y=0<b?a.getDouble():NaN;this.z=16<b?a.getDouble():NaN;this.m=24<b?a.getDouble():NaN}}function ShpPolygon(a,b){ShpPolyline.apply(this,[a,b]);this.type=ShpType.SHAPE_POLYGON}
function ShpPolyline(a,b){this.type=ShpType.SHAPE_POLYLINE;this.rings=[];if(a){if(a.getLength()-a.position<b)throw new ShpError("Not a Polygon record (too small)");a.bigEndian=!1;this.box={x:a.getDouble(),y:a.getDouble(),width:a.getDouble(),height:a.getDouble()};for(var c=a.getSLong(),e=a.getSLong(),d=[];c--;){var f=a.getSLong();d.push(f)}for(c=[];e--;)c.push(new ShpPoint(a,16));e=0;for(d.shift();d.length;)f=d.shift(),this.rings.push(c.splice(0,f-e)),e=f;this.rings.push(c)}}
function ShpError(a,b){this.msg=a;this.id=b;this.toString=function(){return this.msg}}ShpError.ERROR_UNDEFINED=0;ShpError.ERROR_NODATA=1;
